---
- name: Customize issue
  shell: echo "CentOS 7 Customized by NUO" > /etc/issue ; echo >> /etc/issue

- name: Customize issue.net
  shell: echo "CentOS 7 Customized by NUO" > /etc/issue.net; echo >> /etc/issue.net

- name: Customize motd
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Disable SELinux
  selinux: 
    state: disabled 

- name: Yum update cache
  yum:
    update_cache: yes

- name: Remove firewalld
  yum: 
    name: firewalld
    state: absent

- name: Upgrade system
  yum: 
    name: '*'
    state: latest
    update_only: yes
    #update_cache: yes

- name: Install Git, tcpdump, nc,curl, wget, epel-release, python-setuptools and vim
  yum: 
    name: curl,wget,vim,epel-release,git,nmap-ncat,tcpdump,python-setuptools
    state: present

- name: Install pip
  command: easy_install pip

