---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# Prepare CentOS based Linux hosts
- hosts: centos
  user: centos
  become: yes
  vars:
    inproxy: false
  #environment:
  #  HTTP_PROXY: http://proxy-dmz.example.com:3128
  #  https_proxy: http://proxy-dmz.example.com:3128
  #  http_proxy: http://proxy-dmz.example.com:3128
  #  HTTPS_PROXY: http://proxy-dmz.example.com:3128
  roles:
    - roles/centos

- hosts: centos-okd
  user: centos
  become: yes
  vars:
    inproxy: false
  #environment:
  #  HTTP_PROXY: http://proxy-dmz.example.com:3128
  #  https_proxy: http://proxy-dmz.example.com:3128
  #  http_proxy: http://proxy-dmz.example.com:3128
  #  HTTPS_PROXY: http://proxy-dmz.example.com:3128
  roles:
    - roles/centos-okd

- hosts: centos-okd-par
  user: centos
  become: yes
  vars:
    inproxy: false
  #environment:
  #  HTTP_PROXY: http://proxy-dmz.example.com:3128
  #  https_proxy: http://proxy-dmz.example.com:3128
  #  http_proxy: http://proxy-dmz.example.com:3128
  #  HTTPS_PROXY: http://proxy-dmz.example.com:3128
  roles:
    - roles/centos-okd-par

# Prepare Ubuntu based Linux hosts
- hosts: ubuntu
  user: ubuntu
  become: yes
  vars:
    inproxy: false
  environment:
    HTTP_PROXY: http://proxy-dmz.example.com:3128
    https_proxy: http://proxy-dmz.example.com:3128
    http_proxy: http://proxy-dmz.example.com:3128
    HTTPS_PROXY: http://proxy-dmz.example.com:3128
  roles: 
    - roles/ubuntu

# Prepare CentOS based Jenkins slaves
- hosts: centos-slaves
  user: centos
  become: yes
  vars:
    inproxy: false
  environment:
    HTTP_PROXY: http://proxy-dmz.example.com:3128
    https_proxy: http://proxy-dmz.example.com:3128
    http_proxy: http://proxy-dmz.example.com:3128
    HTTPS_PROXY: http://proxy-dmz.example.com:3128
  roles:
    - roles/centos-slaves

# Prepare Ubuntu based OKD host
- hosts: ubuntu-okd
  user: ubuntu
  become: yes
  vars:
    inproxy: false
  roles:
    - roles/ubuntu-okd
