---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# Prepare CentOS based Linux hosts
- hosts: centos
  user: centos
  become: yes
  vars:
    inproxy: false
  environment:
    HTTP_PROXY: http://proxy-dmz.intel.com:911
    https_proxy: http://proxy-dmz.intel.com:911
    http_proxy: http://proxy-dmz.intel.com:911
    HTTPS_PROXY: http://proxy-dmz.intel.com:911
  roles:
    - roles/centos

# Prepare Ubuntu based Linux hosts
- hosts: ubuntu
  user: ubuntu
  become: yes
  vars:
    inproxy: true
  environment:
    HTTP_PROXY: http://proxy-dmz.intel.com:911
    https_proxy: http://proxy-dmz.intel.com:911
    http_proxy: http://proxy-dmz.intel.com:911
    HTTPS_PROXY: http://proxy-dmz.intel.com:911
  roles: 
    - roles/ubuntu

# Prepare CentOS based Jenkins slaves
- hosts: centos-slaves
  user: centos
  become: yes
  vars:
    inproxy: true
  environment:
    HTTP_PROXY: http://proxy-dmz.intel.com:911
    https_proxy: http://proxy-dmz.intel.com:911
    http_proxy: http://proxy-dmz.intel.com:911
    HTTPS_PROXY: http://proxy-dmz.intel.com:911
  roles:
    - roles/centos-slaves

# Prepare Ubuntu based Jenkins slaves
- hosts: ubuntu-slaves
  user: ubuntu
  become: yes
  vars:
    inproxy: true
  environment:
    HTTP_PROXY: http://proxy-dmz.intel.com:911
    https_proxy: http://proxy-dmz.intel.com:911
    http_proxy: http://proxy-dmz.intel.com:911
    HTTPS_PROXY: http://proxy-dmz.intel.com:911
  roles:
    - roles/ubuntu-slaves
