---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# Prepare CentOS based Linux hosts
- hosts: centos
  user: centos
  become: yes
  vars:
    inproxy: false
  roles:
    - roles/centos

# Prepare Ubuntu based Linux hosts
- hosts: ubuntu
  user: ubuntu
  become: yes
  vars:
    inproxy: true 
  roles: 
    - roles/ubuntu

# Prepare CentOS based Jenkins slaves
- hosts: centos-slaves
  user: centos
  become: yes
  vars:
    inproxy: true
  roles:
    - roles/centos-slaves

