---
- name: Docker installer
  copy: 
    src: indocker.sh
    dest: /root/indocker.sh
    owner: root
    mode: 750

- name: Install Docker
  shell: cd /root && /root/indocker.sh

- name: Configure proxy for Docker step 1 create docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Create proxy conf file
  copy:
    src: http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Daemon Reload (Systemd)
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Chamaleon Socks
  copy:
    src: chameleonsocks.sh
    dest: /root
    owner: root
    group: root
    mode: 0755

- name: Chamaleon Exceptions
  copy:
    src: chameleonsocks.exceptions
    dest: /root
    owner: root
    group: root
    mode: 0644

- name: Installer script
  copy:
    src: install.sh
    dest: /root
    owner: root
    group: root
    mode: 0755

- name: Install Chamaleon Socks
  command: bash /root/install.sh