---
- name: Customize issue
  shell: echo "Ubuntu Customized by NUO" > /etc/issue ; echo >> /etc/issue

- name: Customize issue.net
  shell: echo "Ubuntu Customized by NUO" > /etc/issue.net; echo >> /etc/issue.net

- name: Customize motd
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name:
  apt:
    update_cache: yes

- name: Update OS
  apt: 
    name: '*'
    state: latest

- name: Install curl, wget, vim, tmux,nc, git, Python
  apt: 
    name: curl,wget,vim,tmux,netcat-openbsd,git,python,python-pip
    state: present

