---
- name: Customize issue
  shell: echo "CentOS 7 Customized by NUO" > /etc/issue ; echo >> /etc/issue

- name: Customize issue.net
  shell: echo "CentOS 7 Customized by NUO" > /etc/issue.net; echo >> /etc/issue.net

- name: Customize motd
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Enable SELinux
  selinux: 
    state: enforcing 
    policy: targeted

- name: Yum update cache
  yum:
    update_cache: yes

- name: Upgrade system
  yum: 
    name: '*'
    state: latest
    update_only: yes
    #update_cache: yes

- name: Install Git, firewalld, tcpdump, nc,curl, wget, epel-release, python-setuptools, docker and vim
  yum: 
    name: firewalld,curl,wget,vim,epel-release,git,nmap-ncat,tcpdump,python-setuptools,docker
    state: present

- name: Enable FirewallD
  systemd:
    state: started
    name: firewalld
    enabled: yes

- name: Enable Docker
  systemd:
    state: started
    name: docker
    enabled: yes

#- name: Create new dockerc  FirewallD Zone for OKD
#  command: firewall-cmd --permanent --new-zone dockerc

- name: Enable firewall TCP ports
  firewalld: 
    port: 22-12000/tcp
    permanent: yes
    zone: dockerc
    state: enabled

- name: Enable firewall UDP ports
  firewalld: 
    port: 53/udp
    permanent: yes
    zone: dockerc
    state: enabled

- firewalld:
    zone: dockerc
    interface: enp0s8
    permanent: yes
    state: enabled

- name: Install pip
  command: easy_install pip

#- name : Download OKD oc client tool
#  get_url:
#    url: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
#    dest: /root/oc.tgz
#    mode: '0440'

#- name: Create target dir
#  file:
#    path: /opt/oc

#- name: Untar oc client tool
#  unarchive:
#    src: /root/oc.tgz
#    dest: /opt/oc

- name: Install OKD
  command: oc cluster up
